apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/KingSlayer260/k8s-gitops.git"
    targetRevision: HEAD
    path: charts/webapp
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    namespace: web
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
